### ISSUE TITLE
помогите с IMPORT в home assistant

### ISSUE THREAD

**Issue by Seva44** [no-plagiarism/pymorphy3#24]
я установил pymorphy3 в HA через pip в терминале, но при запуске программы ошибка - ModuleNotFoundError: No module named "pymorphy3'

**Comment by insolor** [comment]
Типичная ситуация — запускаете не тем интерпретатором (не той версии, не из того виртуального окружения), для которого установили. Это в целом не связано именно с pymorphy2/3.

**Comment by Seva44** [comment]
но как мне поступить чтобы решить проблему? Переустановить?

**Comment by insolor** [comment]
Я без понятия как home assistant запускается (вообще очень мало контекста даете). Если он запускается через командную строку условно `python home_assistant.py`, пробуйте не просто через pip устанавливать, а через `python -m pip install pymorphy3`, чтобы гарантированно для того же интерпретатора pip запускался.
